Estimates and routerArray
yaxis-project/metavault pull request #114
Opened 2021-10-21 14:39 UTC by GainsGoblin

Fixes:
- Fixed a lot of swap path logic in strategies.
- Added harvest estimations to all strategies.
- BaseStrategy now uses routerArray to swap between routers during harvest.
- SetRouter now can modify routerArray and approves all needed tokens for all routers.
- Harvester now harvests using _estimates array instead of individual parameters.

2021-10-31 18:02 UTC, uN2RVw5q reviewed
Some general comments, the most important one is issues in computing estimates and lack of tests for `getEstimates`.

2021-11-01 14:18 UTC, gpersoon commented
At the _harvest functions:
Either use arrayCounter everywhere were applicable (more readable, but slightly more gas)
Or (if you really want to save gas):
Add comments where arrayCounter is replaced with constants (e.g. 0 / i+1)
After the _extraRewardsLength loop, arrayCounter can be calculated directly:
arrayCounter = _extraRewardsLength + 1;
and no need to increase arrayCounter in the loop;
The last increase "arrayCounter += 2;" for example in ETHConvexStrategy.sol isn't necessary

2021-11-01 14:24 UTC, gpersoon commented
Why isn't getEstimates() using safemath consistently? (now it's mix of mul / sub / div / - )

2021-11-01 15:06 UTC, gpersoon commented
I don't think the following constructions in getEstimates() are valid:
function getEstimates() public view returns (uint256[] memory _estimates) {
    _estimates[0]= ...
    _estimates[_estimates.length] = ...
    
I can't get them working in remix. It does compile but I get an invalid opcode when executing the code.
I think you should allocate memory first and then index the items, something like:
 _estimates = new uint[](crvRewards.extraRewardsLength() + 5);

2021-11-01 15:06 UTC, gpersoon commented
in getEstimates()
_slippage is always used as: ONE_HUNDRED_PERCENT - _slippage
might as well calculate that directly to save some gas:
uint256 _notSlippage = ONE_HUNDRED_PERCENT - IHarvester(manager.harvester()).slippage();

2021-11-08 15:18 UTC, transferAndCall requested changes

2021-11-08 15:18 UTC, transferAndCall commented on test/v3/ConvexStrategy3Crv.test.js
> +        manager.connect(deployer).setHarvester(harvester.address);
```suggestion
        await manager.connect(deployer).setHarvester(harvester.address);
```

2021-11-08 15:18 UTC, transferAndCall commented on test/v3/GeneralConvexStrategy.test.js
> +        manager.connect(deployer).setHarvester(harvester.address);
```suggestion
        await manager.connect(deployer).setHarvester(harvester.address);
```

2021-11-08 15:18 UTC, transferAndCall commented on test/v3/MIMConvexStrategy.test.js
> +        manager.connect(deployer).setHarvester(harvester.address);
```suggestion
        await manager.connect(deployer).setHarvester(harvester.address);
```

2021-11-08 15:18 UTC, transferAndCall commented on test/v3/NativeStrategyCurve3Crv.test.js
> +        manager.connect(deployer).setHarvester(harvester.address);
```suggestion
        await manager.connect(deployer).setHarvester(harvester.address);
```

2021-11-08 15:18 UTC, transferAndCall commented on contracts/v3/strategies/ETHConvexStrategy.sol
> +      	uint256 wethAmount;
Please fix this formatting.

2021-11-08 18:17 UTC, GainsGoblin commented on contracts/v3/strategies/ETHConvexStrategy.sol
> +      	uint256 wethAmount;
Fixed formatting.

2021-11-08 19:11 UTC, merged